#
# @author Daniel Marcenco (danielm@saltedge.com)
# Copyright (c) 2022 Salt Edge.
#

source 'https://rubygems.org'
gem 'sinatra'               # Sinatra is a DSL for quickly creating web applications in Ruby with minimal effort.
gem 'sinatra-contrib'       # Collection of useful Sinatra extensions

# other dependencies
gem 'rake'                 # Rake is a Make-like program implemented in Ruby
gem 'sinatra-activerecord' # ActiveRecord implementation
gem 'sqlite3'              # SQLite DB
gem 'json'                 # JSON implementation
gem 'rqrcode'              # QR code generator
gem 'rest-client'
gem 'pry-byebug'
gem 'jwt', '~> 2.2'
gem 'sidekiq'
gem 'redis'
gem 'rack-contrib'

group :development do
  gem 'rubocop', require: false
  gem 'rubocop-rspec'
end

group :test do
  gem 'rack-test'           # Rack::Test is a layer on top of Rack's MockRequest
  gem 'rspec'               # BDD for Ruby
  gem 'database_cleaner'    # Strategies for cleaning databases. Can be used to ensure a clean state for testing.
  gem 'capybara'            # Feature tests
  gem 'rack_session_access' # Middleware that supports a user in managing sessions independently
  gem 'factory_bot_rails'
end
